# Generated by Django 3.2.12 on 2022-04-11 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial_squashed_squashed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingressotransfer',
            options={'verbose_name': 'ingresso transfer', 'verbose_name_plural': 'ingressos transfers'},
        ),
    ]
