# Generated by Django 3.2.12 on 2022-04-11 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial_squashed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IngressoTransfer',
        ),
    ]
