# Generated by Django 3.2.12 on 2022-03-18 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial_squashed_0009_auto_20220308_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngressoTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateTimeField(blank=True, null=True)),
                ('current_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ingressos', to='eventos.participante')),
                ('ingresso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='eventos.ingresso')),
                ('previous_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfered_ingressos', to='eventos.participante')),
            ],
            options={
                'verbose_name': 'ingresso transfer',
                'verbose_name_plural': 'ingressos transfers',
            },
        ),
    ]
