# Generated by Django 3.2.10 on 2021-12-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_lote_preco_organizador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='preco_organizador',
        ),
        migrations.AlterField(
            model_name='participante',
            name='categoria',
            field=models.CharField(choices=[('socio', 'Sócio'), ('n_socio', 'Não sócio'), ('convidado', 'Convidado'), ('organizador', 'Organizador')], default='n_socio', max_length=12),
        ),
    ]
