# Generated by Django 3.2.13 on 2022-06-09 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20220608_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='convidados',
            field=models.ManyToManyField(blank=True, related_name='convidados', to='eventos.Convidado'),
        ),
        migrations.AddField(
            model_name='evento',
            name='participantes',
            field=models.ManyToManyField(blank=True, to='eventos.Participante'),
        ),
        migrations.AlterField(
            model_name='convidado',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evento', to='eventos.evento'),
        ),
    ]
