# Generated by Django 3.2.12 on 2022-04-11 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20220411_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingressotransfer',
            name='current_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingressos_recebidos', to='eventos.participante'),
        ),
        migrations.AlterField(
            model_name='ingressotransfer',
            name='ingresso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferências', to='eventos.ingresso'),
        ),
        migrations.AlterField(
            model_name='ingressotransfer',
            name='previous_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingressos_transferidos', to='eventos.participante'),
        ),
    ]
