# Generated by Django 3.2.12 on 2022-04-11 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20220411_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingressotransfer',
            options={'verbose_name': 'transferência de ingresso',
                     'verbose_name_plural': 'transferências de ingressos'},
        ),
    ]
