# Generated by Django 3.2.10 on 2022-01-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_auto_20220117_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresso',
            name='status',
            field=models.CharField(choices=[('invalido', 'Inválido'), ('pago', 'Pago'), ('aguardando', 'Aguradando pagamento'), ('pendente', 'Pendente'), ('cancelado', 'Cancelado')], default='pendente', max_length=12),
        ),
    ]
