# Generated by Django 3.2.10 on 2021-12-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_auto_20211226_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresso',
            name='data_compra',
            field=models.DateField(auto_now_add=True),
        ),
    ]
