# Generated by Django 3.2.12 on 2022-02-20 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_alter_ingresso_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='convidado',
            name='evento',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='evento', to='eventos.evento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='convidados',
            field=models.ManyToManyField(
                blank=True, related_name='convidados', to='eventos.Convidado'),
        ),
    ]
