# Generated by Django 3.2.12 on 2022-04-11 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_create_igresso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingressotransfer',
            name='current_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ingressos', to='eventos.participante'),
        ),
        migrations.AlterField(
            model_name='ingressotransfer',
            name='ingresso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='eventos.ingresso'),
        ),
        migrations.AlterField(
            model_name='ingressotransfer',
            name='previous_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfered_ingressos', to='eventos.participante'),
        ),
    ]
