# Generated by Django 3.2.12 on 2022-02-20 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_auto_20220220_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convidado',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evento', to='eventos.evento'),
        ),
    ]
