# Generated by Django 3.2.12 on 2022-02-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_alter_convidado_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='convites_disponiveis',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
