# Generated by Django 3.2.10 on 2021-12-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_convidado_aprovado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresso',
            name='stripe_checkout_id',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='ingresso',
            name='stripe_checkout_url',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='participante',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ingresso',
            name='status',
            field=models.CharField(choices=[('pago', 'Pago'), ('pendente', 'Pendente'), ('cancelado', 'Cancelado')], default='pendente', max_length=12),
        ),
    ]
