# Generated by Django 3.2.12 on 2022-03-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_participante_convites_disponiveis'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='exclusivo_socios',
            field=models.BooleanField(default=False),
        ),
    ]
