# Generated by Django 3.2.12 on 2022-03-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_evento_exclusivo_socios'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='presencial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ingresso',
            name='status',
            field=models.CharField(choices=[('invalido', 'Inválido'), ('pago', 'Pago'), ('aguardando', 'Aguradando pagamento'), ('pendente', 'Pendente'), ('cancelado', 'Cancelado'), ('expirado', 'Expirado')], default='pendente', max_length=255),
        ),
    ]
