# Generated by Django 3.2.12 on 2022-06-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_item_is_variation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['is_variation']},
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, help_text='Image proportions: 1:1', null=True, upload_to='store/images/items'),
        ),
    ]
