# Generated by Django 3.2.12 on 2022-06-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_cart_checked_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='checked_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
