# Generated by Django 3.2.13 on 2022-06-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20220609_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='max_per_member',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of items per member', null=True),
        ),
    ]
