# Generated by Django 3.2.9 on 2021-11-29 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('stripe_price_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(default='00000000', max_length=8)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('apelido', models.CharField(blank=True, max_length=100, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('is_socio', models.BooleanField(default=False)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=250, null=True)),
                ('stripe_portal_url', models.CharField(blank=True, max_length=250, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_id', models.CharField(blank=True, max_length=100, null=True)),
                ('checkout_url', models.CharField(blank=True, max_length=400, null=True)),
                ('data_pagamento', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='Pendente', max_length=15)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='core.socio')),
                ('tipo_plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoplano')),
            ],
        ),
    ]
