# Generated by Django 3.2.12 on 2022-03-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='verified_email',
            field=models.BooleanField(default=False),
        ),
    ]
