# Generated by Django 3.2.12 on 2022-05-23 17:13

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='declaracao_matricula',
            field=models.FileField(blank=True, null=True, upload_to=core.models.socio_dir),
        ),
        migrations.AddField(
            model_name='socio',
            name='vaccine_card',
            field=models.FileField(blank=True, null=True, upload_to=core.models.socio_dir),
        ),
    ]
