# Generated by Django 3.2.9 on 2021-12-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='turma',
            field=models.CharField(default='00', max_length=2),
        ),
    ]
