# Generated by Django 3.2.12 on 2022-03-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_socio_verified_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
