# Generated by Django 3.2.12 on 2022-04-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_featurepost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featurepost',
            options={'verbose_name': 'feature post', 'verbose_name_plural': 'feature posts'},
        ),
        migrations.AddField(
            model_name='featurepost',
            name='button_target',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
