# Generated by Django 3.2.9 on 2021-12-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_socio_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='short_checkout_url',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
