# Generated by Django 3.2.9 on 2021-12-10 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pagamento_short_checkout_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='short_checkout_url',
        ),
    ]
