# Generated by Django 3.2.12 on 2022-04-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220412_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurepost',
            name='image',
            field=models.ImageField(upload_to='feature_posts/'),
        ),
    ]
