# Generated by Django 3.2.9 on 2021-12-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_pagamento_short_checkout_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='turma',
            field=models.CharField(default='MED: 00', max_length=10),
        ),
    ]
