# Generated by Django 3.2.9 on 2021-12-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_socio_whatsapp_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
