# Generated by Django 3.2.13 on 2022-06-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='first_teamers',
            new_name='first_team',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='confirmeds',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='presents',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='status',
        ),
        migrations.AddField(
            model_name='schedule',
            name='description',
            field=models.TextField(default='teste'),
            preserve_default=False,
        ),
    ]
