# Generated by Django 3.2.13 on 2022-06-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20220608_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('S', 'Scheduled'), ('W', 'Waiting Participants'), ('C', 'Confirmed'), ('R', 'Reviewing'), ('E', 'Ended')], default='S', max_length=1),
        ),
    ]
