# Generated by Django 3.2.13 on 2022-06-08 14:27

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0003_schedule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='location',
            field=models.CharField(default='Location', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='max_participants',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='min_participants',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='users_confirmed',
            field=models.ManyToManyField(blank=True, related_name='confirmed_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedule',
            name='users_present',
            field=models.ManyToManyField(blank=True, related_name='present_schedules', to=settings.AUTH_USER_MODEL),
        ),
    ]
