# Generated by Django 3.2.13 on 2022-06-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_auto_20220608_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('W', 'Waiting'), ('C', 'Confirmed'), ('E', 'Ended')], default='W', max_length=1),
        ),
    ]
