# Generated by Django 3.2.12 on 2022-03-13 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('description', models.TextField(verbose_name='descrição')),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('IN_PROGRESS', 'Em andamento'), (
                    'CLOSED', 'Fechado')], default='OPEN', max_length=255, verbose_name='status')),
                ('priority', models.CharField(choices=[('LOW', 'Baixa'), ('MEDIUM', 'Média'), (
                    'HIGH', 'Alta')], max_length=255, verbose_name='prioridade')),
                ('category', models.CharField(choices=[('ASSOCIACAO', 'Associação'), ('BATERIA', 'Bateria'), ('ESPORTES', 'Esportes'), (
                    'EVENTOS', 'Eventos'), ('LOJA', 'Loja'), ('SITE', 'Site'), ('OUTRA', 'Outra')], max_length=255, verbose_name='categoria')),
                ('created_at', models.DateTimeField(
                    auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(
                    auto_now=True, verbose_name='atualizado em')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='issues', to='core.socio', verbose_name='autor')),
            ],
            options={
                'verbose_name': 'solicitação',
                'verbose_name_plural': 'solicitações',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='descrição')),
                ('created_at', models.DateTimeField(
                    auto_now_add=True, verbose_name='criado em')),
                ('author', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='core.socio', verbose_name='autor')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='comments', to='help.issue', verbose_name='solicitação')),
            ],
            options={
                'verbose_name': 'comentário',
                'verbose_name_plural': 'comentários',
                'ordering': ['created_at'],
            },
        ),
    ]
