# Generated by Django 3.2.12 on 2022-03-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_auto_20220312_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Baixa'), ('MEDIUM', 'Média'), ('HIGH', 'Alta')], max_length=255, verbose_name='prioridade'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Aberto'), ('IN_PROGRESS', 'Em andamento'), ('CLOSED', 'Fechado')], default='OPEN', max_length=255, verbose_name='status'),
        ),
    ]
