# Generated by Django 3.2.10 on 2021-12-13 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conta',
            options={'verbose_name': 'conta', 'verbose_name_plural': 'contas'},
        ),
        migrations.AlterModelOptions(
            name='movimentacao',
            options={'verbose_name': 'movimentação', 'verbose_name_plural': 'movimentações'},
        ),
    ]
