# Generated by Django 3.2.12 on 2022-05-24 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resgate',
        ),
    ]
