# Generated by Django 3.2.12 on 2022-03-01 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resgate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('valor_calangos', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolvida', models.BooleanField(default=False)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resgates', to='bank.conta')),
            ],
            options={
                'verbose_name': 'resgate',
                'verbose_name_plural': 'resgates',
            },
        ),
    ]
