# Generated by Django 3.2.9 on 2021-11-29 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20211129_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='conta_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_destino', to='bank.conta'),
        ),
    ]
