# Generated by Django 3.2.9 on 2021-11-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_alter_movimentacao_conta_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='calangos',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Transacao',
        ),
    ]
