# Generated by Django 3.2.12 on 2022-05-31 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_payment_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
