# Generated by Django 3.2.9 on 2021-11-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_auto_20211129_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='resolvida_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
