# Generated by Django 3.2.12 on 2022-05-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_payment_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(default='PENDENTE', max_length=50),
        ),
    ]
