# Generated by Django 3.2.9 on 2021-11-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_movimentacao_resolvida_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='resolvida_em',
            field=models.DateField(blank=True, null=True),
        ),
    ]
