# Generated by Django 3.2.9 on 2021-11-29 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_alter_movimentacao_resolvida_em'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacao',
            name='resolvida',
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='resolvida_em',
        ),
    ]
