# Generated by Django 3.2.12 on 2022-05-31 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(editable=False, max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='bank/attachments/')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='bank.payment')),
            ],
        ),
    ]
