# Generated by Django 3.2.9 on 2021-11-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_auto_20211129_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='resolvida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='resolvida_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
