# Generated by Django 3.2.9 on 2021-11-30 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_auto_20211129_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='conta_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_destino', to='bank.conta'),
        ),
    ]
