# Generated by Django 3.2.9 on 2021-11-30 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_alter_movimentacao_conta_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='estornada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='estornada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='conta_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_origem', to='bank.conta'),
        ),
    ]
