# Generated by Django 3.2.13 on 2022-06-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_alter_payment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('ST', 'Stripe'), ('PX', 'PIX')], max_length=2),
        ),
    ]
