# Generated by Django 3.2.13 on 2022-06-07 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_alter_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='method',
            new_name='method_deprecated',
        ),
    ]
