# Generated by Django 3.2.13 on 2022-06-07 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0014_auto_20220607_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_method',
            new_name='method',
        ),
    ]
