# Generated by Django 3.2.9 on 2021-11-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='produtos',
            field=models.ManyToManyField(blank=True, to='ecommerce.ProdutoPedido'),
        ),
    ]
