# Generated by Django 3.2.12 on 2022-03-24 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial_squashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco_atleta',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='variacaoproduto',
            name='preco_atleta',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
