# Generated by Django 3.2.9 on 2021-12-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='stripe_short_checkout_url',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
