# Generated by Django 3.2.12 on 2022-04-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial_squashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variacaoproduto',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='variacaoproduto',
            name='preco_atleta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='variacaoproduto',
            name='preco_socio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='variacaoproduto',
            name='preco_staff',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='preço diretor'),
        ),
    ]
