# Generated by Django 3.2.10 on 2022-01-19 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='nome do produto'),
        ),
        migrations.AlterField(
            model_name='variacaoproduto',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='variação'),
        ),
    ]
