# Generated by Django 3.2.12 on 2022-03-31 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_produto_exclusivo_competidor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='exclusivo_competidor',
        ),
    ]
