# Generated by Django 3.2.9 on 2021-12-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_carrinho_stripe_short_checkout_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
