# Generated by Django 3.2.10 on 2022-01-22 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20220118_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtopedido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='ecommerce.produto'),
        ),
    ]
