# Generated by Django 3.2.10 on 2022-01-22 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_alter_produtopedido_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='stripe_price_id',
            field=models.DecimalField(
                decimal_places=2, max_digits=8, default=0),
        ),
        migrations.AlterField(
            model_name='variacaoproduto',
            name='stripe_price_id',
            field=models.DecimalField(
                decimal_places=2, max_digits=8, default=0),
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='stripe_price_id',
            new_name='preco_staff',
        ),
        migrations.RenameField(
            model_name='variacaoproduto',
            old_name='stripe_price_id',
            new_name='preco_staff',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='stripe_product_id',
        )
    ]
