# Generated by Django 3.2.10 on 2021-12-16 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_produto_is_hidden'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VariacaoProdutos',
            new_name='VariacaoProduto',
        ),
    ]
