# Generated by Django 3.2.10 on 2022-02-04 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_alter_produtopedido_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='stripe_price_id',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='stripe_product_id',
        ),
        migrations.RemoveField(
            model_name='variacaoproduto',
            name='stripe_price_id',
        ),
    ]
