# Generated by Django 3.2.10 on 2022-02-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20220204_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco_staff',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='preço diretor'),
        ),
        migrations.AddField(
            model_name='produtopedido',
            name='preco_staff',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='variacaoproduto',
            name='preco_staff',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='preço diretor'),
        ),
    ]
