# Generated by Django 3.2.10 on 2022-02-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_custom_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtopedido',
            name='preco_staff',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
