# Generated by Django 3.2.10 on 2021-12-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='status',
            field=models.CharField(choices=[('criado', 'Criado'), ('aguardando', 'Aguardando pagamento'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='criado', max_length=20),
        ),
    ]
