# Generated by Django 3.2.10 on 2022-02-04 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_produtopedido_preco_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco_staff',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='preço diretor'),
        ),
        migrations.AlterField(
            model_name='variacaoproduto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='preço diretor'),
        ),
    ]
