# Generated by Django 3.2.12 on 2022-02-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_produtopedido_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='has_observacoes',
            field=models.BooleanField(default=False),
        ),
    ]
