# Generated by Django 3.2.12 on 2022-05-30 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='member',
            new_name='membership',
        ),
    ]
