# Generated by Django 3.2.12 on 2022-05-31 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0008_alter_membership_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='ref',
            field=models.CharField(choices=[('ST', 'Stripe'), ('N', 'None')], max_length=20),
        ),
    ]
