# Generated by Django 3.2.13 on 2022-06-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0010_auto_20220601_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='ref',
            field=models.CharField(choices=[('ST', 'Stripe'), ('PX', 'Pix'), ('N', 'None')], max_length=20),
        ),
    ]
