# Generated by Django 3.2.13 on 2022-06-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0011_alter_membership_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
