# Generated by Django 3.2.13 on 2022-06-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0012_membershipplan_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='days',
            field=models.IntegerField(default=30),
        ),
    ]
