# Generated by Django 3.2.13 on 2022-06-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0013_membershipplan_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='ref',
            field=models.CharField(choices=[('ST', 'Stripe'), ('PX', 'PIX'), ('N', 'None')], max_length=20),
        ),
    ]
