# Generated by Django 3.2.12 on 2022-03-29 15:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('socio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                 related_name='competidor', to='core.socio')),
            ],
            options={
                'verbose_name': 'competidor',
                'verbose_name_plural': 'competidores',
            },
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('Diretoria', 'Diretoria'), ('Coord', 'Coordenação'), (
                    'Esporte', 'Esporte'), ('Bateria', 'Bateria'), ('Social', 'Ação social'), ('Outra', 'Outra')], max_length=10)),
                ('competidores', models.ManyToManyField(blank=True,
                 related_name='modalidades', to='atividades.Competidor')),
                ('responsavel', models.ForeignKey(blank=True, editable=False, null=True,
                 on_delete=django.db.models.deletion.CASCADE, related_name='modalidades', to='core.socio')),
            ],
        ),
        migrations.CreateModel(
            name='Programacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('local', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('competidores_minimo', models.IntegerField(default=0)),
                ('competidores_maximo', models.IntegerField(default=0)),
                ('estado', models.CharField(default='Agendado', max_length=20)),
                ('competidores_confirmados', models.ManyToManyField(
                    blank=True, related_name='confirmados_na_programacao', to='atividades.Competidor')),
                ('competidores_presentes', models.ManyToManyField(
                    blank=True, related_name='presentes_na_programacao', to='atividades.Competidor')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='programacao', to='atividades.modalidade')),
                ('grupo_whatsapp_url', models.CharField(
                    blank=True, max_length=150, null=True)),
                ('notify', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'programação',
                'verbose_name_plural': 'programações',
            },
        ),
    ]
