# Generated by Django 3.2.10 on 2021-12-13 12:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_alter_socio_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='competidor', to='core.socio')),
            ],
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('Diretoria', 'Diretoria'), ('Coord', 'Coordenação'), ('Esporte', 'Esporte'), ('Bateria', 'Bateria'), ('Social', 'Ação social'), ('Outra', 'Outra')], max_length=100)),
                ('membros', models.ManyToManyField(to='atividades.Competidor')),
            ],
        ),
        migrations.CreateModel(
            name='Programacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('hora', models.TimeField(default=django.utils.timezone.now)),
                ('local', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('competidores_confirmados', models.ManyToManyField(blank=True, related_name='confirmados_na_programacao', to='atividades.Competidor')),
                ('competidores_presentes', models.ManyToManyField(blank=True, related_name='presentes_na_programacao', to='atividades.Competidor')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programacao', to='atividades.modalidade')),
            ],
        ),
    ]
