# Generated by Django 3.2.10 on 2022-02-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacao',
            name='grupo_whatsapp_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
