# Generated by Django 3.2.12 on 2022-05-10 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programacao',
            options={'ordering': ['data_hora'], 'verbose_name': 'programação', 'verbose_name_plural': 'programações'},
        ),
    ]
