# Generated by Django 3.2.10 on 2021-12-13 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0002_rename_membros_modalidade_competidores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competidor',
            options={'verbose_name': 'competidor', 'verbose_name_plural': 'competidores'},
        ),
        migrations.AlterModelOptions(
            name='programacao',
            options={'verbose_name': 'programação', 'verbose_name_plural': 'programações'},
        ),
    ]
