# Generated by Django 3.2.10 on 2021-12-13 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0004_auto_20211213_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programacao',
            name='data',
        ),
        migrations.RemoveField(
            model_name='programacao',
            name='hora',
        ),
        migrations.AddField(
            model_name='programacao',
            name='data_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='programacao',
            name='estado',
            field=models.CharField(default='Agendado', max_length=20),
        ),
    ]
