# Generated by Django 3.2.10 on 2021-12-18 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_socio_avatar'),
        ('atividades', '0005_auto_20211213_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalidade',
            name='responsavel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='modalidades', to='core.socio'),
            preserve_default=False,
        ),
    ]
