# Generated by Django 3.2.10 on 2021-12-22 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_socio_avatar'),
        ('atividades', '0007_alter_modalidade_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalidade',
            name='responsavel',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modalidades', to='core.socio'),
        ),
    ]
