# Generated by Django 3.2.10 on 2021-12-27 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_alter_ingresso_data_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='lote',
            name='quantidade_restante',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
