# Generated by Django 3.2.10 on 2021-12-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_auto_20211226_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='convidado',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
    ]
