# Generated by Django 3.2.10 on 2021-12-27 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_auto_20211227_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingresso',
            name='stripe_checkout_url',
        ),
    ]
