# Generated by Django 3.2.10 on 2022-01-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0011_auto_20220116_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/'),
        ),
        migrations.AlterField(
            model_name='ingresso',
            name='status',
            field=models.CharField(choices=[('pago', 'Pago'), ('aguardando', 'Aguradando pagamento'), ('pendente', 'Pendente'), ('cancelado', 'Cancelado')], default='pendente', max_length=12),
        ),
        migrations.AlterField(
            model_name='ingresso',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
