# Generated by Django 3.2.10 on 2022-01-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_auto_20220117_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='fechado',
            field=models.BooleanField(default=True),
        ),
    ]
