# Generated by Django 3.2.12 on 2022-03-26 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled', max_length=100)),
                ('content', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.CASCADE, to='core.socio')),
                ('likes', models.ManyToManyField(blank=True,
                 related_name='files_likes', to='core.Socio')),
                ('viewers', models.ManyToManyField(blank=True,
                 related_name='files_viwers', to='core.Socio')),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
