# Generated by Django 3.2.12 on 2022-02-26 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled', max_length=100)),
                ('content', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.socio')),
                ('likes', models.ManyToManyField(blank=True, related_name='files_likes', to='core.Socio')),
                ('viewers', models.ManyToManyField(blank=True, related_name='files_viwers', to='core.Socio')),
            ],
        ),
    ]
