# Generated by Django 3.2.12 on 2022-05-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='nome')),
                ('socio_benefits', models.TextField(verbose_name='socio benefits')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descrição')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partnerships/logos', verbose_name='logo')),
                ('url', models.URLField(blank=True, null=True, verbose_name='url')),
            ],
            options={
                'verbose_name': 'partnership',
                'verbose_name_plural': 'partnerships',
            },
        ),
    ]
