# Generated by Django 3.2.12 on 2022-05-30 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import members.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(default='00000000', max_length=8)),
                ('group', models.CharField(default='MED: 00', max_length=7)),
                ('name', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=124)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('birth_date', models.DateField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=members.models.member_avatar_dir)),
                ('rg', models.CharField(blank=True, max_length=15, null=True)),
                ('cpf', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='members.member')),
            ],
        ),
    ]
