# Generated by Django 3.2.12 on 2022-05-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='title',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
